# fly.toml app configuration file generated for yelp-dataset-demo on 2023-09-06T15:43:07+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yelp-dataset-demo"
primary_region = "bos"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
